---
## Self-contained include tasks (independent of the role) to idempotently create a host principal and its keytab.
## Include parameters:
## - "_kadmin_cmd": the kadmin cmd (usually 'kadmin.local')
## - "_realm_name": the kerberos realm name
## - "_principal": the principal without the realm OR alternatively you can provide
## - "_primary": (alternative) the principal's primary
## - "_instance": (optional) the principal's instance
## - "_keytab" (optional): the keytab file to create
## - "_keytab_owner" (optional): the keytab file's owner

- set_fact:
    _principal: "{{ _primary + (('/'+_instance) if _instance is defined  else '') }}"
  when: _principal is not defined

- name: Create kerberos principal {{ _principal }}
  command: >
    {{ _kadmin_cmd }} -q "addprinc -randkey {{ _principal }}@{{ _realm_name|upper() }}"
  register: addprinc_result
  changed_when:
    - addprinc_result.stderr
    - not (addprinc_result.stderr is search("Principal or policy already exists while creating") )

- name: Fail if the principal could not be created
  fail:
    msg: The {{ _principal }} principal could not be created. Error is {{ addprinc_result.stderr }}
  when: >
    addprinc_result is failed
    or not (addprinc_result.stdout is search("Principal .* created")
    or addprinc_result.stderr is search("Principal or policy already exists while creating"))

- block:
    - name: Check if keytab file exists
      stat:
        path: "{{ _keytab }}"
      register: keytab

    - name: Check if principal exists in the keytab
      shell: |
        set -o pipefail;
        klist -kte {{ _keytab }} | grep -E "{{ _principal }}"
      args:
        executable: /bin/bash
      register: klist_kte_result
      changed_when: false
      failed_when: klist_kte_result.rc not in [0,1]
      when: keytab.stat.exists

    - name: Create keytab for the principal
      command: >
        {{ _kadmin_cmd }} -q
        "ktadd -k {{ _keytab }} {{ _principal }}@{{ _realm_name|upper() }}"
      when: >
        not keytab.stat.exists
        or klist_kte_result.rc != 0
     
    - name: Set keytab owner
      file:
        path: "{{ _keytab }}"
        owner:  "{{ _keytab_owner }}"
      when: _keytab_owner is defined
  when: _keytab is defined
